/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zhc_u_demo_JNI_b */

#ifndef _Included_com_zhc_u_demo_JNI_b
#define _Included_com_zhc_u_demo_JNI_b
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_u_demo_JNI_b
 * Method:    f0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhc_u_demo_JNI_b_f0
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
