/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zhc_u_demo_JNI_a */

#ifndef _Included_com_zhc_u_demo_JNI_a
#define _Included_com_zhc_u_demo_JNI_a
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_u_demo_JNI_a
 * Method:    f1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zhc_u_demo_JNI_a_f1
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
