/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class s_a */

#ifndef _Included_s_a
#define _Included_s_a
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
